### PR TITLE
First edit

### PR DESCRIPTION
**Pull request by derekriemer**
some recommended changes. Please comment first.

### CODE REVIEW

**Comment by josephsl** [comment]
Looks fine.

* Bug hunting: I advise removing that review for now.
* Advanced security review: I guess we can introduce this once we get NVDA in more corporate environments where security is discussed.

Thanks.

**Comment by derekriemer** [comment]
> * Bug hunting: I advise removing that review for now.

Again, my concern is that we can potentially point out bugs and try to just break things, but the best way to break things is for users to just use the addon. The best bug hunting review would be to ask users to intentionally make the addon do things the author didn't intend. I think this may be better suited for the nvda-addons list, where a large base of users ready to beta test addons exist already.

> * Advanced security review: I guess we can introduce this once we get NVDA in more corporate environments where security is discussed.

My concern with this is it gives the illusion that security can be easily manually audited, but no one on our team is an expert in doing security audits. Also, I don't want addon authors thinking that their addon is free from security defects because they passed a security review from an unpaid volunteer whose expertise is accessibility.

**Comment by josephsl** [comment]
Hi, ion this case, let’s keep bug hunting review and ask users to try unexpected procedures with the add-on. As for security, I’ll leave it up to you as to how you’d like to word it. Thanks.

**Comment by derekriemer** [comment]
If you are okay with this, please merge it. Otherwise, I'll change whatever needs changing. 
Thanks.

**Review by josephsl — APPROVED** [review]

**Comment by nvdaes** [comment]
Should be the review process included in a link?
Adriani Botez suggested changes to the process too.
Thanks

**Pull request merged**
